[package]
name = "biu-tauri"
version = "1.12.0"
description = "music application based on bilibili api"
authors = ["wood3n", "wmsans"]
license = "PolyForm-Noncommercial-1.0.0"
repository = "https://github.com/wood3n/biu.git"
homepage = "https://github.com/wood3n/biu#readme"
edition = "2021"
keywords = [
  "music",
  "music desktop application",
  "bilibili music application",
  "frontend",
  "react",
  "typescript",
  "tauri"
]
rust-version = "1.77.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.5.3", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.9.5", features = ["tray-icon"] }
tauri-plugin-log = "2"
tauri-plugin-dialog = "2.4.2"
tauri-plugin-shell = "2.3.3"
tauri-plugin-http = "2.5.4"
reqwest = { version = "0.12.25", default-features = false, features = ["rustls-tls", "json", "stream", "cookies"] }
tokio = { version = "1.48.0", features = ["fs", "io-util", "process"] }
font-kit = "0.14.3"
open = "5.3.3"
futures-util = "0.3.31"
urlencoding = "2.1.3"
uuid = { version = "1.19.0", features = ["v4", "fast-rng"] }
thiserror = "2.0.17"
anyhow = "1.0.100"
md5 = "0.8.0"
reqwest_cookie_store = "0.9.0"
tauri-plugin-single-instance = "2.3.6"
tauri-plugin-global-shortcut = "2.3.1"
mimalloc = "0.1.48"
url = "2.5.7"

[profile.release]
panic = "abort" # Removes stack unwind code
codegen-units = 1 # Allows for maximum optimization at the cost of compile time
lto = true # Link Time Optimization
opt-level = "z" # Optimize for size (or "3" for speed, "s" is a balance)
strip = false # Remove debug symbols
